del align2d.ali
del align2d.pap
del salign_pair.*
del salign.ali
del *.log
del output.*
del fix_positions_salign.pap
del 1is3A.*
del 1is3A-it.*
del *_fit.pdb
del 1bml.sol
del suboptimal_alignments.out
del 1bml.psa
del fm07254_out*.ali
del malign.ali
